### ISSUE TITLE
python setup.py build broken

### ISSUE THREAD

**Issue by astrofrog** [mwcraig/ipyevents#2]
If I try doing ``python setup.py build`` I get:

```
$ python setup.py build
setup.py entered
$PATH=/opt/local/bin:/opt/local/sbin:/Users/tom/.gem/ruby/2.0.0/bin:/Users/tom/.rvm/gems/ruby-2.3.0/bin:/Users/tom/.rvm/gems/ruby-2.3.0@global/bin:/Users/tom/.rvm/rubies/ruby-2.3.0/bin:/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin:/Users/tom/miniconda3/envs/dev/bin:/Users/tom/miniconda3/bin:/Applications/git-annex.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/usr/local/heroku/bin:/Users/tom/usr/Montage_v3.3/bin:/Users/tom/Library/Python/3.4/bin:/Users/tom/usr/hyperion/bin:/Users/tom/Dropbox/usr/bin:/Users/tom/usr/bin:/Users/tom/Library/Python/3.4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/tom/.rvm/bin:/usr/local/opt/go/libexec/bin:/Users/tom/.go/bin
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    exec(f.read(), {}, version_ns)
  File "<string>", line 9, in <module>
KeyError: 'dev'
```

**Comment by mwcraig** [comment]
Closed by #3
